stages:
  - build
  - deploy

.releases: &releases
  only:
    - /^\d[\d\.]*(-(alpha|beta)\d+)?$/

build:
  stage: build
  only:
    - tags
    - web
  script:
    - /bin/sh release.sh -d
  artifacts:
    paths:
      - .release/VuhDo/
      - .release/VuhDoOptions/
      - .release/*.zip
  
curseforge:
  <<: *releases
  stage: deploy
  environment:
    name: CurseForge
    url: https://www.curseforge.com/wow/addons/vuhdo
  script:
    - /bin/sh release.sh -ocelzWHG

wowinterface:
  <<: *releases
  stage: deploy
  environment:
    name: WoWInterface
    url: https://www.wowinterface.com/downloads/info14239-VuhDo.html
  script:
    - /bin/sh release.sh -ocelzLHG

gitlab:
  <<: *releases
  stage: deploy
  environment:
    name: GitLab
    url: https://gitlab.vuhdo.io/vuhdo/vuhdo/releases
  script:
    - /bin/sh release.sh -ocelzLWH
