stages:
  - build
  - deploy

.releases: &releases
  only:
    - /^v\d[\d\.]*(-classic-?)?(-(alpha|beta))?(-\d+)?$/
    
before_script:
  - apk add --no-cache bash curl git subversion zip jq luacheck pandoc

luacheck:
  stage: build
  script:
    - luacheck . -q && echo "Lua check passed!" || echo "Lua check failed!"

package:
  <<: *releases
  stage: deploy
  only:
    - tags
    - web
  script:
    - cd .release
    - chmod +x ./release.sh
    - ./release.sh
  artifacts:
    paths:
      - .release/VuhDo/
      - .release/VuhDoOptions/
      - .release/*.zip
  
