VUHDO_FLAVOR_RETAIL = 1;
VUHDO_FLAVOR_FOREVER = 2;

VUHDO_FLAVOR_SPEC_SPECIALIZATIONS = 1;
VUHDO_FLAVOR_SPEC_TALENT_GROUPS = 2;

VUHDO_FLAVOR_REQ_CLASS = 1;
VUHDO_FLAVOR_REQ_POWER = 2;
VUHDO_FLAVOR_REQ_FEATURE = 3;

VUHDO_FLAVOR_FEATURE_WAR_MODE = 1;
VUHDO_FLAVOR_FEATURE_SPELL_TRACE = 2;
VUHDO_FLAVOR_FEATURE_ALTERNATE_POWERS = 3;
VUHDO_FLAVOR_FEATURE_CLUSTER = 4;
VUHDO_FLAVOR_FEATURE_TRAIL_OF_LIGHT = 5;
