blank_issues_enabled: true
contact_links:
  - name: VuhDo guide on Icy-Veins
    url: https://www.icy-veins.com/forums/topic/11805-vuhdo-a-comprehensive-guide/
    about: Getting started with VuhDo and answers to common setup questions.
  - name: VuhDo profiles, key layouts and bouquets on wago.io
    url: https://wago.io
    about: Download user created VuhDo profiles, key layouts and custom bouquets.
