-- Resurrection spells by class
VUHDO_RESURRECTION_SPELLS = {
	["PALADIN"] = {
		[1] = { VUHDO_SPELL_ID.ABSOLUTION, VUHDO_SPELL_ID.REDEMPTION, VUHDO_SPELL_ID.INTERCESSION },
		[2] = { VUHDO_SPELL_ID.REDEMPTION, VUHDO_SPELL_ID.INTERCESSION },
		[3] = { VUHDO_SPELL_ID.REDEMPTION, VUHDO_SPELL_ID.INTERCESSION },
	},
	["SHAMAN"] = { 
		[1] = { VUHDO_SPELL_ID.ANCESTRAL_SPIRIT },
		[2] = { VUHDO_SPELL_ID.ANCESTRAL_SPIRIT },
		[3] = { VUHDO_SPELL_ID.ANCESTRAL_VISION, VUHDO_SPELL_ID.ANCESTRAL_SPIRIT },
	},
	["DRUID"] = {
		[1] = { VUHDO_SPELL_ID.REVIVE, VUHDO_SPELL_ID.REBIRTH },
		[2] = { VUHDO_SPELL_ID.REVIVE, VUHDO_SPELL_ID.REBIRTH },
		[3] = { VUHDO_SPELL_ID.REVIVE, VUHDO_SPELL_ID.REBIRTH },
		[4] = { VUHDO_SPELL_ID.REVITALIZE, VUHDO_SPELL_ID.REVIVE, VUHDO_SPELL_ID.REBIRTH },
	},
	["PRIEST"] = {
		[1] = { VUHDO_SPELL_ID.MASS_RESURRECTION, VUHDO_SPELL_ID.RESURRECTION },
		[2] = { VUHDO_SPELL_ID.MASS_RESURRECTION, VUHDO_SPELL_ID.RESURRECTION },
		[3] = { VUHDO_SPELL_ID.RESURRECTION },
	},
	["DEATHKNIGHT"] = {
		[1] = { VUHDO_SPELL_ID.RAISE_ALLY },
		[2] = { VUHDO_SPELL_ID.RAISE_ALLY },
		[3] = { VUHDO_SPELL_ID.RAISE_ALLY },
	},
	["MONK"] = {
		[1] = { VUHDO_SPELL_ID.RESUSCITATE },
		[2] = { VUHDO_SPELL_ID.REAWAKEN, VUHDO_SPELL_ID.RESUSCITATE },
		[3] = { VUHDO_SPELL_ID.RESUSCITATE },
	},
	["EVOKER"] = {
		[1] = { VUHDO_SPELL_ID.RETURN },
		[2] = { VUHDO_SPELL_ID.MASS_RETURN, VUHDO_SPELL_ID.RETURN },
		[3] = { VUHDO_SPELL_ID.RETURN },
	},
};

--
VUHDO_BUFF_REMOVAL_CHARM_SPELLS = {
	[VUHDO_SPELL_ID.CLEANSE_SPIRIT] = true,
	[VUHDO_SPELL_ID.CYCLONE] = true,
	[VUHDO_SPELL_ID.NATURES_CURE] = true,
	[VUHDO_SPELL_ID.WIND_SHEAR] = true,
};
