VUHDO_RANGE_SPELLS_REMAP = {
	["HELPFUL"] = {
		[VUHDO_SPELL_ID.LIVING_FLAME] = { VUHDO_SPELL_ID.CHRONO_FLAME, VUHDO_SPELL_ID.EMERALD_BLOSSOM },
		[VUHDO_SPELL_ID.DETOX] = { VUHDO_SPELL_ID.VIVIFY },
	},
	["HARMFUL"] = {
		[VUHDO_SPELL_ID.SMITE] = { VUHDO_SPELL_ID.SHADOW_WORD_PAIN },
		[VUHDO_SPELL_ID.LIVING_FLAME] = { VUHDO_SPELL_ID.AZURE_STRIKE },
		[VUHDO_SPELL_ID.LIGHTNING_BOLT] = { VUHDO_SPELL_ID.FLAME_SHOCK },
	},
};

VUHDO_PET_RANGE_SPELLS = {
	["HUNTER"] = 136,
	["WARLOCK"] = 755,
	["DEATHKNIGHT"] = 47541,
};

VUHDO_RESURRECTION_RANGE_SPELLS = {
	["DRUID"] = VUHDO_SPELL_ID.REBIRTH,
	["PRIEST"] = VUHDO_SPELL_ID.RESURRECTION,
	["PALADIN"] = VUHDO_SPELL_ID.INTERCESSION,
	["SHAMAN"] = VUHDO_SPELL_ID.ANCESTRAL_SPIRIT,
	["MONK"] = VUHDO_SPELL_ID.RESUSCITATE,
	["DEATHKNIGHT"] = VUHDO_SPELL_ID.RAISE_ALLY,
	["WARLOCK"] = VUHDO_SPELL_ID.SOULSTONE,
	["EVOKER"] = VUHDO_SPELL_ID.RETURN,
};
