VUHDO_RESURRECTION_SPELLS = {
	["PALADIN"] = {
		[1] = { VUHDO_SPELL_ID.REDEMPTION },
		[2] = { VUHDO_SPELL_ID.REDEMPTION },
	},
	["SHAMAN"] = {
		[1] = { VUHDO_SPELL_ID.ANCESTRAL_SPIRIT },
		[2] = { VUHDO_SPELL_ID.ANCESTRAL_SPIRIT },
	},
	["DRUID"] = {
		[1] = { VUHDO_SPELL_ID.REBIRTH },
		[2] = { VUHDO_SPELL_ID.REBIRTH },
	},
	["PRIEST"] = {
		[1] = { VUHDO_SPELL_ID.RESURRECTION },
		[2] = { VUHDO_SPELL_ID.RESURRECTION },
	},
};

--
VUHDO_BUFF_REMOVAL_CHARM_SPELLS = { };
