VUHDO_AURA_IGNORE_LIST_DEFAULTS = {
	[26013] = true, -- Deserter
	[2479] = true, -- Honorless Target
	[11196] = true, -- Recently Bandaged
	[15007] = true, -- Resurrection Sickness
	[6788] = true, -- Weakened Soul
};



VUHDO_DEFAULT_RANGE_SPELLS = {
	["WARRIOR"] = {
		["HELPFUL"] = { },
		["HARMFUL"] = { VUHDO_SPELL_ID.TAUNT },
	},
	["ROGUE"] = {
		["HELPFUL"] = { },
		["HARMFUL"] = { VUHDO_SPELL_ID.SINISTER_STRIKE },
	},
	["HUNTER"] = {
		["HELPFUL"] = { },
		["HARMFUL"] = { VUHDO_SPELL_ID.ARCANE_SHOT },
	},
	["PALADIN"] = {
		["HELPFUL"] = { VUHDO_SPELL_ID.FLASH_OF_LIGHT, VUHDO_SPELL_ID.HOLY_LIGHT },
		["HARMFUL"] = { VUHDO_SPELL_ID.HAMMER_OF_JUSTICE },
	},
	["MAGE"] = {
		["HELPFUL"] = { VUHDO_SPELL_ID.BUFF_ARCANE_INTELLECT },
		["HARMFUL"] = { 116, 133 }, -- VUHDO_SPELL_ID.FROSTBOLT, VUHDO_SPELL_ID.FIREBALL
	},
	["WARLOCK"] = {
		["HELPFUL"] = { },
		["HARMFUL"] = { VUHDO_SPELL_ID.SHADOW_BOLT },
	},
	["SHAMAN"] = {
		["HELPFUL"] = { VUHDO_SPELL_ID.HEALING_WAVE },
		["HARMFUL"] = { VUHDO_SPELL_ID.FLAME_SHOCK, VUHDO_SPELL_ID.LIGHTNING_BOLT },
	},
	["DRUID"] = {
		["HELPFUL"] = { VUHDO_SPELL_ID.REJUVENATION },
		["HARMFUL"] = { VUHDO_SPELL_ID.MOONFIRE },
	},
	["PRIEST"] = {
		["HELPFUL"] = { VUHDO_SPELL_ID.FLASH_HEAL },
		["HARMFUL"] = { VUHDO_SPELL_ID.SHADOW_WORD_PAIN, VUHDO_SPELL_ID.SMITE },
	},
	["DEATHKNIGHT"] = {
		["HELPFUL"] = { },
		["HARMFUL"] = { },
	},
	["MONK"] = {
		["HELPFUL"] = { },
		["HARMFUL"] = { },
	},
	["DEMONHUNTER"] = {
		["HELPFUL"] = { },
		["HARMFUL"] = { },
	},
	["EVOKER"] = {
		["HELPFUL"] = { },
		["HARMFUL"] = { },
	},
};



VUHDO_CLASS_DEFAULT_SPELL_ASSIGNMENT = {
	["PALADIN"] = {
		["1"] = { "", "1", VUHDO_SPELL_ID.FLASH_OF_LIGHT },
		["2"] = { "", "2", VUHDO_SPELL_ID.HOLY_LIGHT },
		["3"] = { "", "3", "dropdown" },

		["alt1"] = { "alt-", "1", "target" },
		["alt2"] = { "alt-", "2", "focus" },
		["alt3"] = { "alt-", "3", "menu" },

		["ctrl1"] = { "ctrl-", "1", VUHDO_SPELL_ID.LAY_ON_HANDS },
		["ctrl2"] = { "ctrl-", "2", VUHDO_SPELL_ID.BLESSING_OF_PROTECTION },
		["ctrl3"] = { "ctrl-", "3", "menu" },

		["shift1"] = { "shift-", "1", VUHDO_SPELL_ID.PALA_CLEANSE },
		["shift2"] = { "shift-", "2", VUHDO_SPELL_ID.PURIFY },
		["shift3"] = { "shift-", "3", "menu" },
	},

	["SHAMAN"] = {
		["1"] = { "", "1", VUHDO_SPELL_ID.HEALING_WAVE },
		["2"] = { "", "2", VUHDO_SPELL_ID.LESSER_HEALING_WAVE },
		["3"] = { "", "3", "dropdown" },
		["4"] = { "", "4", VUHDO_SPELL_ID.CHAIN_HEAL },

		["alt1"] = { "alt-", "1", "target" },
		["alt2"] = { "alt-", "2", "focus" },
		["alt3"] = { "alt-", "3", "menu" },

		["ctrl1"] = { "ctrl-", "1", VUHDO_SPELL_ID.ANCESTRAL_SPIRIT },
		["ctrl2"] = { "ctrl-", "2", VUHDO_SPELL_ID.CURE_POISON_SHAMAN },
		["ctrl3"] = { "ctrl-", "3", "menu" },

		["shift1"] = { "shift-", "1", VUHDO_SPELL_ID.CURE_POISON_SHAMAN },
		["shift2"] = { "shift-", "2", VUHDO_SPELL_ID.CURE_DISEASE_SHAMAN },
		["shift3"] = { "shift-", "3", "menu" },
	},

	["PRIEST"] = {
		["1"] = { "", "1", VUHDO_SPELL_ID.FLASH_HEAL },
		["2"] = { "", "2", VUHDO_SPELL_ID.RENEW },
		["3"] = { "", "3", "dropdown" },
		["4"] = { "", "4", VUHDO_SPELL_ID.GREATER_HEAL },

		["alt1"] = { "alt-", "1", "target" },
		["alt2"] = { "alt-", "2", "focus" },
		["alt3"] = { "alt-", "3", "menu" },

		["ctrl1"] = { "ctrl-", "1", VUHDO_SPELL_ID.PRAYER_OF_HEALING },
		["ctrl2"] = { "ctrl-", "2", VUHDO_SPELL_ID.DISPEL_MAGIC },
		["ctrl3"] = { "ctrl-", "3", "menu" },

		["shift1"] = { "shift-", "1", VUHDO_SPELL_ID.POWERWORD_SHIELD },
		["shift2"] = { "shift-", "2", VUHDO_SPELL_ID.CURE_DISEASE_PRIEST },
		["shift3"] = { "shift-", "3", "menu" },
	},

	["DRUID"] = {
		["1"] = { "", "1", VUHDO_SPELL_ID.HEALING_TOUCH },
		["2"] = { "", "2", VUHDO_SPELL_ID.REJUVENATION },
		["3"] = { "", "3", "dropdown" },
		["4"] = { "", "4", VUHDO_SPELL_ID.REGROWTH },

		["alt1"] = { "alt-", "1", "target" },
		["alt2"] = { "alt-", "2", "focus" },
		["alt3"] = { "alt-", "3", "menu" },

		["ctrl1"] = { "ctrl-", "1", VUHDO_SPELL_ID.INNERVATE },
		["ctrl2"] = { "ctrl-", "2", VUHDO_SPELL_ID.REMOVE_CURSE },
		["ctrl3"] = { "ctrl-", "3", "menu" },

		["shift1"] = { "shift-", "1", VUHDO_SPELL_ID.CURE_POISON_DRUID },
		["shift2"] = { "shift-", "2", VUHDO_SPELL_ID.ABOLISH_POISON },
		["shift3"] = { "shift-", "3", "menu" },
	},
};



VUHDO_DEFAULT_AURA_GROUPS_FLAVOR_ENTRIES = {
	["RESTORATION_DRUID_HOTS"] = {
		["type"] = 2,
		["entries"] = {
			{ ["entryType"] = 1, ["value"] = 774, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1058, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1430, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 2090, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 2091, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 3627, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 8910, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9839, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9840, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9841, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 8936, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 8938, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 8939, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 8940, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 8941, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9750, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9856, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9857, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9858, ["mine"] = true, ["others"] = false },
		},
		["displayName"] = nil,
		["enabled"] = true,
		["priority"] = 50,
		["colorType"] = VUHDO_AURA_GROUP_COLOR_OFF,
		["canColorBar"] = false,
		["canColorText"] = false,
		["canGlowBar"] = false,
		["glowBarColor"] = nil,
		["unitScope"] = VUHDO_AURA_GROUP_UNIT_SCOPE_FRIENDLY,
		["ignoreList"] = { },
		["sound"] = nil,
	},
	["DISCIPLINE_PRIEST_HOTS"] = {
		["type"] = 2,
		["entries"] = {
			{ ["entryType"] = 1, ["value"] = 17, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 592, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 600, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 3747, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6065, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6066, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10898, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10899, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10900, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10901, ["mine"] = true, ["others"] = false },
		},
		["displayName"] = nil,
		["enabled"] = true,
		["priority"] = 50,
		["colorType"] = VUHDO_AURA_GROUP_COLOR_OFF,
		["canColorBar"] = false,
		["canColorText"] = false,
		["canGlowBar"] = false,
		["glowBarColor"] = nil,
		["unitScope"] = VUHDO_AURA_GROUP_UNIT_SCOPE_FRIENDLY,
		["ignoreList"] = { },
		["sound"] = nil,
	},
	["HOLY_PRIEST_HOTS"] = {
		["type"] = 2,
		["entries"] = {
			{ ["entryType"] = 1, ["value"] = 139, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6074, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6075, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6076, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6077, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6078, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10927, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10928, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10929, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25315, ["mine"] = true, ["others"] = false },
		},
		["displayName"] = nil,
		["enabled"] = true,
		["priority"] = 50,
		["colorType"] = VUHDO_AURA_GROUP_COLOR_OFF,
		["canColorBar"] = false,
		["canColorText"] = false,
		["canGlowBar"] = false,
		["glowBarColor"] = nil,
		["unitScope"] = VUHDO_AURA_GROUP_UNIT_SCOPE_FRIENDLY,
		["ignoreList"] = { },
		["sound"] = nil,
	},
	["HOLY_PALADIN_HOTS"] = {
		["type"] = 2,
		["entries"] = {
			{ ["entryType"] = 1, ["value"] = 1022, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 5599, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10278, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6940, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 20729, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1044, ["mine"] = true, ["others"] = false },
		},
		["displayName"] = nil,
		["enabled"] = true,
		["priority"] = 50,
		["colorType"] = VUHDO_AURA_GROUP_COLOR_OFF,
		["canColorBar"] = false,
		["canColorText"] = false,
		["canGlowBar"] = false,
		["glowBarColor"] = nil,
		["unitScope"] = VUHDO_AURA_GROUP_UNIT_SCOPE_FRIENDLY,
		["ignoreList"] = { },
		["sound"] = nil,
	},
	["RAID_BUFFS"] = {
		["type"] = 2,
		["entries"] = {
			{ ["entryType"] = 1, ["value"] = 1243, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1244, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1245, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 2791, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10937, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10938, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 21562, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 21564, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 14752, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 14818, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 14819, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 27841, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 27681, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 976, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10957, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10958, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 27683, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1126, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 5232, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 5234, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6756, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 8907, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9884, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9885, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 21849, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 21850, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 467, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 782, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1075, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 8914, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9756, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 9910, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1459, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1460, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1461, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10156, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 10157, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 23028, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19740, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19834, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19835, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19836, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19837, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19838, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25291, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19742, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19850, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19852, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19853, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19854, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25290, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 20217, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19977, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19978, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 19979, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 1038, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25898, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25894, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25918, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25782, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25916, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25890, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25895, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6673, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 5242, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 6192, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 11549, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 11550, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 11551, ["mine"] = true, ["others"] = false },
			{ ["entryType"] = 1, ["value"] = 25289, ["mine"] = true, ["others"] = false },
		},
		["displayName"] = nil,
		["enabled"] = true,
		["priority"] = 50,
		["colorType"] = VUHDO_AURA_GROUP_COLOR_OFF,
		["canColorBar"] = false,
		["canColorText"] = false,
		["canGlowBar"] = false,
		["glowBarColor"] = nil,
		["unitScope"] = VUHDO_AURA_GROUP_UNIT_SCOPE_FRIENDLY,
		["ignoreList"] = { },
		["sound"] = nil,
	},
};
