VUHDO_FLAVOR_RULES = {
	["SPEC_MODEL"] = VUHDO_FLAVOR_SPEC_TALENT_GROUPS,
	["CLASSES"] = {
		[VUHDO_ID_WARRIORS] = true,
		[VUHDO_ID_ROGUES] = true,
		[VUHDO_ID_HUNTERS] = true,
		[VUHDO_ID_PALADINS] = true,
		[VUHDO_ID_MAGES] = true,
		[VUHDO_ID_WARLOCKS] = true,
		[VUHDO_ID_SHAMANS] = true,
		[VUHDO_ID_DRUIDS] = true,
		[VUHDO_ID_PRIESTS] = true,
	},
	["POWER_TYPES"] = {
		[VUHDO_UNIT_POWER_MANA] = true,
		[VUHDO_UNIT_POWER_RAGE] = true,
		[VUHDO_UNIT_POWER_FOCUS] = true,
		[VUHDO_UNIT_POWER_ENERGY] = true,
		[VUHDO_UNIT_POWER_COMBO_POINTS] = true,
	},
	["FEATURES"] = {
		[VUHDO_FLAVOR_FEATURE_WAR_MODE] = false,
		[VUHDO_FLAVOR_FEATURE_SPELL_TRACE] = false,
		[VUHDO_FLAVOR_FEATURE_ALTERNATE_POWERS] = false,
		[VUHDO_FLAVOR_FEATURE_CLUSTER] = false,
		[VUHDO_FLAVOR_FEATURE_TRAIL_OF_LIGHT] = false,
	},
	["CLASS_POWER_TYPES"] = {
		[VUHDO_ID_SHAMANS] = VUHDO_UNIT_POWER_MANA,
		[VUHDO_ID_DRUIDS] = VUHDO_UNIT_POWER_MANA,
		[VUHDO_ID_PRIESTS] = VUHDO_UNIT_POWER_MANA,
	},
};
