---------------------------------------
-- Forever overwrites of the shared base
---------------------------------------
VUHDO_SPELL_ID.DISPEL_MAGIC = VUHDO_getSpellInfoSafe(527);
VUHDO_SPELL_ID.HEAL = VUHDO_getSpellInfoSafe(2054);
VUHDO_SPELL_ID.PURIFY = VUHDO_getSpellInfoSafe(1152);
VUHDO_SPELL_ID.REMOVE_CORRUPTION = VUHDO_getSpellInfoSafe(2782);
VUHDO_SPELL_ID.REMOVE_CURSE = VUHDO_getSpellInfoSafe(2782);
VUHDO_SPELL_ID.SOULSTONE = VUHDO_getSpellInfoSafe(20707);
VUHDO_SPELL_ID.HOLY_LIGHT = VUHDO_getSpellInfoSafe(635);
VUHDO_SPELL_ID.HEALING_WAVE = VUHDO_getSpellInfoSafe(331);
VUHDO_SPELL_ID.LIGHTNING_BOLT = VUHDO_getSpellInfoSafe(403);
VUHDO_SPELL_ID.FLAME_SHOCK = VUHDO_getSpellInfoSafe(8050);

VUHDO_SPELL_ID.BUFF_POWER_WORD_FORTITUDE = VUHDO_getSpellInfoSafe(1243);
VUHDO_SPELL_ID.BUFF_ARCANE_BRILLIANCE = VUHDO_getSpellInfoSafe(23028);
VUHDO_SPELL_ID.BUFF_ICE_BLOCK = VUHDO_getSpellInfoSafe(11958);
VUHDO_SPELL_ID.BUFF_INVISIBILITY = VUHDO_getSpellInfoSafe(7870);
VUHDO_SPELL_ID.BUFF_LIGHTNING_SHIELD = VUHDO_getSpellInfoSafe(324);
VUHDO_SPELL_ID.BUFF_GROUNDING_TOTEM = VUHDO_getSpellInfoSafe(8177);
VUHDO_SPELL_ID.BUFF_STONESKIN_TOTEM = VUHDO_getSpellInfoSafe(8071);
VUHDO_SPELL_ID.BUFF_MANA_SPRING_TOTEM = VUHDO_getSpellInfoSafe(5675);
VUHDO_SPELL_ID.BUFF_POISON_CLEANSING_TOTEM = VUHDO_getSpellInfoSafe(8166);
VUHDO_SPELL_ID.BUFF_MANA_TIDE_TOTEM = VUHDO_getSpellInfoSafe(16190);
VUHDO_SPELL_ID.BUFF_WOUND_POISON = VUHDO_getSpellInfoSafe(13218);
VUHDO_SPELL_ID.BUFF_NUMBING_POISON = VUHDO_getSpellInfoSafe(5761);
VUHDO_SPELL_ID.BUFF_INSTANT_POISON = VUHDO_getSpellInfoSafe(8679);



---------------------------------------
-- Forever-only spells
---------------------------------------
VUHDO_SPELL_ID.ABOLISH_DISEASE = VUHDO_getSpellInfoSafe(552);
VUHDO_SPELL_ID.ABOLISH_POISON = VUHDO_getSpellInfoSafe(2893);
VUHDO_SPELL_ID.CURE_DISEASE_PRIEST = VUHDO_getSpellInfoSafe(528);
VUHDO_SPELL_ID.CURE_DISEASE_SHAMAN = VUHDO_getSpellInfoSafe(2870);
VUHDO_SPELL_ID.CURE_POISON_DRUID = VUHDO_getSpellInfoSafe(8946);
VUHDO_SPELL_ID.CURE_POISON_SHAMAN = VUHDO_getSpellInfoSafe(526);
VUHDO_SPELL_ID.REMOVE_LESSER_CURSE = VUHDO_getSpellInfoSafe(475);

VUHDO_SPELL_ID.LESSER_HEAL = VUHDO_getSpellInfoSafe(2050);
VUHDO_SPELL_ID.GREATER_HEAL = VUHDO_getSpellInfoSafe(2060);
VUHDO_SPELL_ID.LESSER_HEALING_WAVE = VUHDO_getSpellInfoSafe(8004);
VUHDO_SPELL_ID.WRATH = VUHDO_getSpellInfoSafe(5176);
VUHDO_SPELL_ID.EARTH_SHOCK = VUHDO_getSpellInfoSafe(8042);
VUHDO_SPELL_ID.HAMMER_OF_JUSTICE = VUHDO_getSpellInfoSafe(853);
VUHDO_SPELL_ID.SINISTER_STRIKE = VUHDO_getSpellInfoSafe(1752);
VUHDO_SPELL_ID.ARCANE_SHOT = VUHDO_getSpellInfoSafe(3044);

-- Priest
VUHDO_SPELL_ID.BUFF_PRAYER_OF_FORTITUDE = VUHDO_getSpellInfoSafe(21562);
VUHDO_SPELL_ID.BUFF_SHADOW_PROTECTION = VUHDO_getSpellInfoSafe(976);
VUHDO_SPELL_ID.BUFF_PRAYER_OF_SHADOW_PROTECTION = VUHDO_getSpellInfoSafe(27683);
VUHDO_SPELL_ID.BUFF_DIVINE_SPIRIT = VUHDO_getSpellInfoSafe(14752);
VUHDO_SPELL_ID.BUFF_PRAYER_OF_SPIRIT = VUHDO_getSpellInfoSafe(27681);
VUHDO_SPELL_ID.BUFF_FEAR_WARD = VUHDO_getSpellInfoSafe(6346);
VUHDO_SPELL_ID.BUFF_INNER_FIRE = VUHDO_getSpellInfoSafe(588);
VUHDO_SPELL_ID.BUFF_SHADOWGUARD = VUHDO_getSpellInfoSafe(18137);
VUHDO_SPELL_ID.BUFF_TOUCH_OF_WEAKNESS = VUHDO_getSpellInfoSafe(2652);

-- Shaman
VUHDO_SPELL_ID.BUFF_ELEMENTAL_FOCUS = VUHDO_getSpellInfoSafe(16246);
VUHDO_SPELL_ID.BUFF_FIRE_RESISTANCE_TOTEM = VUHDO_getSpellInfoSafe(8184);
VUHDO_SPELL_ID.BUFF_FROST_RESISTANCE_TOTEM = VUHDO_getSpellInfoSafe(8181);
VUHDO_SPELL_ID.BUFF_NATURE_RESISTANCE_TOTEM = VUHDO_getSpellInfoSafe(10595);
VUHDO_SPELL_ID.BUFF_SEARING_TOTEM = VUHDO_getSpellInfoSafe(3599);
VUHDO_SPELL_ID.BUFF_FLAMETONGUE_TOTEM = VUHDO_getSpellInfoSafe(8227);
VUHDO_SPELL_ID.BUFF_WINDFURY_TOTEM = VUHDO_getSpellInfoSafe(8512);
VUHDO_SPELL_ID.BUFF_GRACE_OF_AIR = VUHDO_getSpellInfoSafe(8835);
VUHDO_SPELL_ID.BUFF_SENTRY_TOTEM = VUHDO_getSpellInfoSafe(6495);
VUHDO_SPELL_ID.BUFF_WINDWALL_TOTEM = VUHDO_getSpellInfoSafe(15107);
VUHDO_SPELL_ID.BUFF_STRENGTH_OF_EARTH = VUHDO_getSpellInfoSafe(8075);
VUHDO_SPELL_ID.BUFF_STONECLAW_TOTEM = VUHDO_getSpellInfoSafe(5730);
VUHDO_SPELL_ID.BUFF_DISEASE_CLEANSING_TOTEM = VUHDO_getSpellInfoSafe(8170);
VUHDO_SPELL_ID.BUFF_ROCKBITER_WEAPON = VUHDO_getSpellInfoSafe(8017);
VUHDO_SPELL_ID.BUFF_WINDFURY_WEAPON = VUHDO_getSpellInfoSafe(8232);
VUHDO_SPELL_ID.BUFF_FLAMETONGUE_WEAPON = VUHDO_getSpellInfoSafe(8024);
VUHDO_SPELL_ID.BUFF_FROSTBRAND_WEAPON = VUHDO_getSpellInfoSafe(8033);

-- Paladin
VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_KINGS = VUHDO_getSpellInfoSafe(25898);
VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_WISDOM = VUHDO_getSpellInfoSafe(25894);
VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_MIGHT = VUHDO_getSpellInfoSafe(25782);
VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_LIGHT = VUHDO_getSpellInfoSafe(25890);
VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_SALVATION = VUHDO_getSpellInfoSafe(25895);
VUHDO_SPELL_ID.BUFF_RIGHTEOUS_FURY = VUHDO_getSpellInfoSafe(25780);
VUHDO_SPELL_ID.BUFF_BLESSING_OF_KINGS = VUHDO_getSpellInfoSafe(20217);
VUHDO_SPELL_ID.BUFF_BLESSING_OF_WISDOM = VUHDO_getSpellInfoSafe(19742);
VUHDO_SPELL_ID.BUFF_BLESSING_OF_MIGHT = VUHDO_getSpellInfoSafe(19740);
VUHDO_SPELL_ID.BUFF_BLESSING_OF_LIGHT = VUHDO_getSpellInfoSafe(19977);
VUHDO_SPELL_ID.BUFF_BLESSING_OF_SALVATION = VUHDO_getSpellInfoSafe(1038);

-- Druid
VUHDO_SPELL_ID.BUFF_GIFT_OF_THE_WILD = VUHDO_getSpellInfoSafe(21849);
VUHDO_SPELL_ID.BUFF_THORNS = VUHDO_getSpellInfoSafe(467);
VUHDO_SPELL_ID.BUFF_OMEN_OF_CLARITY = VUHDO_getSpellInfoSafe(16864);

-- Hunter
VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_HAWK = VUHDO_getSpellInfoSafe(13165);
VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_MONKEY = VUHDO_getSpellInfoSafe(13163);
VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_CHEETAH = VUHDO_getSpellInfoSafe(5118);
VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_PACK = VUHDO_getSpellInfoSafe(13159);
VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_BEAST = VUHDO_getSpellInfoSafe(13161);
VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_WILD = VUHDO_getSpellInfoSafe(20043);

-- Warlock
VUHDO_SPELL_ID.BUFF_DEMON_SKIN = VUHDO_getSpellInfoSafe(687);
VUHDO_SPELL_ID.BUFF_DEMON_ARMOR = VUHDO_getSpellInfoSafe(706);

-- Mage
VUHDO_SPELL_ID.BUFF_ARCANE_INTELLECT = VUHDO_getSpellInfoSafe(1459);
VUHDO_SPELL_ID.BUFF_MAGE_ARMOR = VUHDO_getSpellInfoSafe(6117);
VUHDO_SPELL_ID.BUFF_FROST_ARMOR = VUHDO_getSpellInfoSafe(168);
VUHDO_SPELL_ID.BUFF_ICE_ARMOR = VUHDO_getSpellInfoSafe(7302);
VUHDO_SPELL_ID.BUFF_AMPLIFY_MAGIC = VUHDO_getSpellInfoSafe(1008);
VUHDO_SPELL_ID.BUFF_DAMPEN_MAGIC = VUHDO_getSpellInfoSafe(604);



--
VUHDO_NAME_TO_SPELL = { };



--
VUHDO_REPLACE_SPELL_NAME = { };



--
VUHDO_NATIVE_ASSIGN_SPELLS = {
	[VUHDO_SPELL_ID.SOULSTONE] = true,
};



--
VUHDO_BATTLE_REZ_ITEM_IDS = { };
