local GROUP_ATK_POWER = {
	VUHDO_SPELL_ID.BUFF_BATTLE_SHOUT,
};

local GROUP_STATS = {
	VUHDO_SPELL_ID.BUFF_MARK_OF_THE_WILD,
	VUHDO_SPELL_ID.BUFF_GIFT_OF_THE_WILD,
};

local GROUP_STAM = {
	VUHDO_SPELL_ID.BUFF_POWER_WORD_FORTITUDE,
	VUHDO_SPELL_ID.BUFF_PRAYER_OF_FORTITUDE,
};

local GROUP_SHADOW = {
	VUHDO_SPELL_ID.BUFF_SHADOW_PROTECTION,
	VUHDO_SPELL_ID.BUFF_PRAYER_OF_SHADOW_PROTECTION,
};

local GROUP_SPIRIT = {
	VUHDO_SPELL_ID.BUFF_DIVINE_SPIRIT,
	VUHDO_SPELL_ID.BUFF_PRAYER_OF_SPIRIT,
};

local GROUP_INT = {
	VUHDO_SPELL_ID.BUFF_ARCANE_INTELLECT,
	VUHDO_SPELL_ID.BUFF_ARCANE_BRILLIANCE,
};

local GROUP_KINGS = {
	VUHDO_SPELL_ID.BUFF_BLESSING_OF_KINGS,
	VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_KINGS,
};

local GROUP_WISDOM = {
	VUHDO_SPELL_ID.BUFF_BLESSING_OF_WISDOM,
	VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_WISDOM,
};

local GROUP_MIGHT = {
	VUHDO_SPELL_ID.BUFF_BLESSING_OF_MIGHT,
	VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_MIGHT,
};

local GROUP_LIGHT = {
	VUHDO_SPELL_ID.BUFF_BLESSING_OF_LIGHT,
	VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_LIGHT,
};

local GROUP_SALVATION = {
	VUHDO_SPELL_ID.BUFF_BLESSING_OF_SALVATION,
	VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_SALVATION,
};

local GROUP_DAMPEN = {
	VUHDO_SPELL_ID.BUFF_DAMPEN_MAGIC,
};

local GROUP_AMPLIFY = {
	VUHDO_SPELL_ID.BUFF_AMPLIFY_MAGIC,
};

local GROUP_ICE_BLOCK = {
	VUHDO_SPELL_ID.BUFF_ICE_BLOCK,
};

local GROUP_INVISIBILITY = {
	VUHDO_SPELL_ID.BUFF_INVISIBILITY,
};


--
-- Buffs per Class
-- Class => BUff-disjunctive-Group => Buff-Overwriting-Group => BuffName, Target type
--
VUHDO_CLASS_BUFFS = {
	-- Priest
	["PRIEST"] = {
		[VUHDO_SPELL_ID.BUFF_POWER_WORD_FORTITUDE] = {
			{ VUHDO_SPELL_ID.BUFF_POWER_WORD_FORTITUDE, VUHDO_BUFF_TARGET_SINGLE, GROUP_STAM },
			{ VUHDO_SPELL_ID.BUFF_PRAYER_OF_FORTITUDE, VUHDO_BUFF_TARGET_GROUP, GROUP_STAM },
		},
		[VUHDO_SPELL_ID.BUFF_SHADOW_PROTECTION] = {
			{ VUHDO_SPELL_ID.BUFF_SHADOW_PROTECTION, VUHDO_BUFF_TARGET_SINGLE, GROUP_SHADOW },
			{ VUHDO_SPELL_ID.BUFF_PRAYER_OF_SHADOW_PROTECTION, VUHDO_BUFF_TARGET_GROUP, GROUP_SHADOW },
		},
		[VUHDO_SPELL_ID.BUFF_DIVINE_SPIRIT] = {
			{ VUHDO_SPELL_ID.BUFF_DIVINE_SPIRIT, VUHDO_BUFF_TARGET_SINGLE, GROUP_SPIRIT, ["manaOnly"] = true },
			{ VUHDO_SPELL_ID.BUFF_PRAYER_OF_SPIRIT, VUHDO_BUFF_TARGET_GROUP, GROUP_SPIRIT, ["manaOnly"] = true },
		},
		[VUHDO_SPELL_ID.BUFF_FEAR_WARD] = {
			{ VUHDO_SPELL_ID.BUFF_FEAR_WARD, VUHDO_BUFF_TARGET_SINGLE },
		},
		[VUHDO_SPELL_ID.BUFF_POWER_INFUSION] = {
			{ VUHDO_SPELL_ID.BUFF_POWER_INFUSION, VUHDO_BUFF_TARGET_UNIQUE },
		},
		[VUHDO_SPELL_ID.BUFF_LEVITATE] = {
			{ VUHDO_SPELL_ID.BUFF_LEVITATE, VUHDO_BUFF_TARGET_SINGLE },
		},
		[VUHDO_SPELL_ID.BUFF_INNER_FIRE] = {
			{ VUHDO_SPELL_ID.BUFF_INNER_FIRE, VUHDO_BUFF_TARGET_SELF },
		},
		[VUHDO_SPELL_ID.BUFF_SHADOWGUARD] = {
			{ VUHDO_SPELL_ID.BUFF_SHADOWGUARD, VUHDO_BUFF_TARGET_SELF },
		},
		[VUHDO_SPELL_ID.BUFF_TOUCH_OF_WEAKNESS] = {
			{ VUHDO_SPELL_ID.BUFF_TOUCH_OF_WEAKNESS, VUHDO_BUFF_TARGET_SELF },
		},
	},

	-- Shaman
	["SHAMAN"] = {
		[VUHDO_I18N_BUFFC_FIRE_TOTEM] = {
			{ VUHDO_SPELL_ID.BUFF_MAGMA_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_FIRE_RESISTANCE_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_FROST_RESISTANCE_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_SEARING_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_FLAMETONGUE_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
		},
		[VUHDO_I18N_BUFFC_AIR_TOTEM] = {
			{ VUHDO_SPELL_ID.BUFF_WINDFURY_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_GROUNDING_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_GRACE_OF_AIR, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_NATURE_RESISTANCE_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_SENTRY_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_WINDWALL_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
		},
		[VUHDO_I18N_BUFFC_EARTH_TOTEM] = {
			{ VUHDO_SPELL_ID.BUFF_EARTHBIND_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_TREMOR_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_STRENGTH_OF_EARTH, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_STONECLAW_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_STONESKIN_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
		},
		[VUHDO_I18N_BUFFC_WATER_TOTEM] = {
			{ VUHDO_SPELL_ID.BUFF_MANA_TIDE_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_HEALING_STREAM_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_MANA_SPRING_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_POISON_CLEANSING_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
			{ VUHDO_SPELL_ID.BUFF_DISEASE_CLEANSING_TOTEM, VUHDO_BUFF_TARGET_TOTEM },
		},
		[VUHDO_SPELL_ID.BUFF_LIGHTNING_SHIELD] = {
			{ VUHDO_SPELL_ID.BUFF_LIGHTNING_SHIELD, VUHDO_BUFF_TARGET_SELF },
		},
		[VUHDO_I18N_BUFFC_WEAPON_ENCHANT] = {
			{ VUHDO_SPELL_ID.BUFF_ROCKBITER_WEAPON, VUHDO_BUFF_TARGET_ENCHANT },
			{ VUHDO_SPELL_ID.BUFF_WINDFURY_WEAPON, VUHDO_BUFF_TARGET_ENCHANT },
			{ VUHDO_SPELL_ID.BUFF_FLAMETONGUE_WEAPON, VUHDO_BUFF_TARGET_ENCHANT },
			{ VUHDO_SPELL_ID.BUFF_FROSTBRAND_WEAPON, VUHDO_BUFF_TARGET_ENCHANT },
		},
		[VUHDO_I18N_BUFFC_WEAPON_ENCHANT_OFF] = {
			{ VUHDO_SPELL_ID.BUFF_ROCKBITER_WEAPON, VUHDO_BUFF_TARGET_ENCHANT_OFF },
			{ VUHDO_SPELL_ID.BUFF_WINDFURY_WEAPON, VUHDO_BUFF_TARGET_ENCHANT_OFF },
			{ VUHDO_SPELL_ID.BUFF_FLAMETONGUE_WEAPON, VUHDO_BUFF_TARGET_ENCHANT_OFF },
			{ VUHDO_SPELL_ID.BUFF_FROSTBRAND_WEAPON, VUHDO_BUFF_TARGET_ENCHANT_OFF },
		},
	},

	-- Paladin
	["PALADIN"] = {
		[VUHDO_SPELL_ID.BUFF_BLESSING_OF_KINGS] = {
			{ VUHDO_SPELL_ID.BUFF_BLESSING_OF_KINGS, VUHDO_BUFF_TARGET_SINGLE, GROUP_KINGS },
			{ VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_KINGS, VUHDO_BUFF_TARGET_GROUP, GROUP_KINGS },
		},
		[VUHDO_SPELL_ID.BUFF_BLESSING_OF_WISDOM] = {
			{ VUHDO_SPELL_ID.BUFF_BLESSING_OF_WISDOM, VUHDO_BUFF_TARGET_SINGLE, GROUP_WISDOM, ["manaOnly"] = true },
			{ VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_WISDOM, VUHDO_BUFF_TARGET_GROUP, GROUP_WISDOM, ["manaOnly"] = true },
		},
		[VUHDO_SPELL_ID.BUFF_BLESSING_OF_MIGHT] = {
			{ VUHDO_SPELL_ID.BUFF_BLESSING_OF_MIGHT, VUHDO_BUFF_TARGET_SINGLE, GROUP_MIGHT },
			{ VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_MIGHT, VUHDO_BUFF_TARGET_GROUP, GROUP_MIGHT },
		},
		[VUHDO_SPELL_ID.BUFF_BLESSING_OF_LIGHT] = {
			{ VUHDO_SPELL_ID.BUFF_BLESSING_OF_LIGHT, VUHDO_BUFF_TARGET_SINGLE, GROUP_LIGHT },
			{ VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_LIGHT, VUHDO_BUFF_TARGET_GROUP, GROUP_LIGHT },
		},
		[VUHDO_SPELL_ID.BUFF_BLESSING_OF_SALVATION] = {
			{ VUHDO_SPELL_ID.BUFF_BLESSING_OF_SALVATION, VUHDO_BUFF_TARGET_SINGLE, GROUP_SALVATION },
			{ VUHDO_SPELL_ID.BUFF_GREATER_BLESSING_OF_SALVATION, VUHDO_BUFF_TARGET_GROUP, GROUP_SALVATION },
		},
		[VUHDO_SPELL_ID.BUFF_RIGHTEOUS_FURY] = {
			{ VUHDO_SPELL_ID.BUFF_RIGHTEOUS_FURY, VUHDO_BUFF_TARGET_SELF },
		},
	},

	-- Druid
	["DRUID"] = {
		[VUHDO_SPELL_ID.BUFF_MARK_OF_THE_WILD] = {
			{ VUHDO_SPELL_ID.BUFF_MARK_OF_THE_WILD, VUHDO_BUFF_TARGET_SINGLE, GROUP_STATS },
			{ VUHDO_SPELL_ID.BUFF_GIFT_OF_THE_WILD, VUHDO_BUFF_TARGET_GROUP, GROUP_STATS },
		},
		[VUHDO_SPELL_ID.BUFF_THORNS] = {
			{ VUHDO_SPELL_ID.BUFF_THORNS, VUHDO_BUFF_TARGET_SINGLE },
		},
		[VUHDO_SPELL_ID.BUFF_OMEN_OF_CLARITY] = {
			{ VUHDO_SPELL_ID.BUFF_OMEN_OF_CLARITY, VUHDO_BUFF_TARGET_SELF },
		},
	},

	-- Warlock
	["WARLOCK"] = {
		[VUHDO_I18N_BUFFC_SKIN] = {
			{ VUHDO_SPELL_ID.BUFF_DEMON_SKIN, VUHDO_BUFF_TARGET_SELF },
			{ VUHDO_SPELL_ID.BUFF_DEMON_ARMOR, VUHDO_BUFF_TARGET_SELF },
		},
	},

	-- Mage
	["MAGE"] = {
		[VUHDO_SPELL_ID.BUFF_ARCANE_INTELLECT] = {
			{ VUHDO_SPELL_ID.BUFF_ARCANE_INTELLECT, VUHDO_BUFF_TARGET_SINGLE, GROUP_INT, ["manaOnly"] = true },
			{ VUHDO_SPELL_ID.BUFF_ARCANE_BRILLIANCE, VUHDO_BUFF_TARGET_GROUP, GROUP_INT, ["manaOnly"] = true },
		},
		[VUHDO_SPELL_ID.BUFF_ICE_BLOCK] = {
			{ VUHDO_SPELL_ID.BUFF_ICE_BLOCK, VUHDO_BUFF_TARGET_SELF },
		},
		[VUHDO_SPELL_ID.BUFF_SLOW_FALL] = {
			{ VUHDO_SPELL_ID.BUFF_SLOW_FALL, VUHDO_BUFF_TARGET_SINGLE },
		},
		[VUHDO_SPELL_ID.BUFF_INVISIBILITY] = {
			{ VUHDO_SPELL_ID.BUFF_INVISIBILITY, VUHDO_BUFF_TARGET_SELF },
		},
		[VUHDO_I18N_BUFFC_ARMOR_MAGE] = {
			{ VUHDO_SPELL_ID.BUFF_MAGE_ARMOR, VUHDO_BUFF_TARGET_SELF },
			{ VUHDO_SPELL_ID.BUFF_FROST_ARMOR, VUHDO_BUFF_TARGET_SELF },
			{ VUHDO_SPELL_ID.BUFF_ICE_ARMOR, VUHDO_BUFF_TARGET_SELF },
		},
		[VUHDO_SPELL_ID.BUFF_AMPLIFY_MAGIC] = {
			{ VUHDO_SPELL_ID.BUFF_AMPLIFY_MAGIC, VUHDO_BUFF_TARGET_SINGLE, GROUP_AMPLIFY },
		},
		[VUHDO_SPELL_ID.BUFF_DAMPEN_MAGIC] = {
			{ VUHDO_SPELL_ID.BUFF_DAMPEN_MAGIC, VUHDO_BUFF_TARGET_SINGLE, GROUP_DAMPEN },
		},
	},

	-- Warrior
	["WARRIOR"] = {
		[VUHDO_SPELL_ID.BUFF_BATTLE_SHOUT] = {
			{ VUHDO_SPELL_ID.BUFF_BATTLE_SHOUT, VUHDO_BUFF_TARGET_RAID, GROUP_ATK_POWER },
		},
	},

	-- Hunter
	["HUNTER"] = {
		[VUHDO_I18N_BUFFC_ASPECT] = {
			{ VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_HAWK, VUHDO_BUFF_TARGET_SELF },
			{ VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_MONKEY, VUHDO_BUFF_TARGET_SELF },
			{ VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_CHEETAH, VUHDO_BUFF_TARGET_SELF },
			{ VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_PACK, VUHDO_BUFF_TARGET_SELF },
			{ VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_BEAST, VUHDO_BUFF_TARGET_SELF },
			{ VUHDO_SPELL_ID.BUFF_ASPECT_OF_THE_WILD, VUHDO_BUFF_TARGET_SELF },
		},
	},

	-- Rogue
	["ROGUE"] = {
		[VUHDO_I18N_BUFFC_WEAPON_ENCHANT] = {
			{ VUHDO_SPELL_ID.BUFF_INSTANT_POISON, VUHDO_BUFF_TARGET_ENCHANT },
			{ VUHDO_SPELL_ID.BUFF_DEADLY_POISON, VUHDO_BUFF_TARGET_ENCHANT },
			{ VUHDO_SPELL_ID.BUFF_WOUND_POISON, VUHDO_BUFF_TARGET_ENCHANT },
			{ VUHDO_SPELL_ID.BUFF_CRIPPLING_POISON, VUHDO_BUFF_TARGET_ENCHANT },
			{ VUHDO_SPELL_ID.BUFF_NUMBING_POISON, VUHDO_BUFF_TARGET_ENCHANT },
		},
		[VUHDO_I18N_BUFFC_WEAPON_ENCHANT_OFF] = {
			{ VUHDO_SPELL_ID.BUFF_INSTANT_POISON, VUHDO_BUFF_TARGET_ENCHANT_OFF },
			{ VUHDO_SPELL_ID.BUFF_DEADLY_POISON, VUHDO_BUFF_TARGET_ENCHANT_OFF },
			{ VUHDO_SPELL_ID.BUFF_WOUND_POISON, VUHDO_BUFF_TARGET_ENCHANT_OFF },
			{ VUHDO_SPELL_ID.BUFF_CRIPPLING_POISON, VUHDO_BUFF_TARGET_ENCHANT_OFF },
			{ VUHDO_SPELL_ID.BUFF_NUMBING_POISON, VUHDO_BUFF_TARGET_ENCHANT_OFF },
		},
	},

	["DEATHKNIGHT"] = { },

	["MONK"] = { },

	["DEMONHUNTER"] = { },

	["EVOKER"] = { },
};



VUHDO_BUFF_WATCH_AURA_SPELL_IDS = {
	[1243] = { 1243, 1244, 1245, 2791, 10937, 10938 }, -- Power Word: Fortitude
	[21562] = { 21562, 21564 }, -- Prayer of Fortitude
	[14752] = { 14752, 14818, 14819, 27841 }, -- Divine Spirit
	[976] = { 976, 10957, 10958 }, -- Shadow Protection
	[588] = { 588, 7128, 602, 1006, 10951, 10952 }, -- Inner Fire
	[1126] = { 1126, 5232, 5234, 6756, 8907, 9884, 9885 }, -- Mark of the Wild
	[21849] = { 21849, 21850 }, -- Gift of the Wild
	[467] = { 467, 782, 1075, 8914, 9756, 9910 }, -- Thorns
	[1459] = { 1459, 1460, 1461, 10156, 10157 }, -- Arcane Intellect
	[1008] = { 1008, 8455, 10169, 10170 }, -- Amplify Magic
	[604] = { 604, 8450, 8451, 10173, 10174 }, -- Dampen Magic
	[6117] = { 6117, 22782, 22783 }, -- Mage Armor
	[168] = { 168, 7300, 7301 }, -- Frost Armor
	[7302] = { 7302, 7320, 10219, 10220 }, -- Ice Armor
	[687] = { 687, 696 }, -- Demon Skin
	[706] = { 706, 1086, 11733, 11734, 11735 }, -- Demon Armor
	[6673] = { 6673, 5242, 6192, 11549, 11550, 11551, 25289 }, -- Battle Shout
	[19740] = { 19740, 19834, 19835, 19836, 19837, 19838, 25291 }, -- Blessing of Might
	[19742] = { 19742, 19850, 19852, 19853, 19854, 25290 }, -- Blessing of Wisdom
	[19977] = { 19977, 19978, 19979 }, -- Blessing of Light
	[25894] = { 25894, 25918 }, -- Greater Blessing of Wisdom
	[25782] = { 25782, 25916 }, -- Greater Blessing of Might
	[13165] = { 13165, 14318, 14319, 14320, 14321, 14322 }, -- Aspect of the Hawk
	[20043] = { 20043, 20190 }, -- Aspect of the Wild
};



VUHDO_AURA_SPELL_VARIANTS = {
	[774] = { 774, 1058, 1430, 2090, 2091, 3627, 8910, 9839, 9840, 9841 }, -- Rejuvenation
	[8936] = { 8936, 8938, 8939, 8940, 8941, 9750, 9856, 9857, 9858 }, -- Regrowth
	[139] = { 139, 6074, 6075, 6076, 6077, 6078, 10927, 10928, 10929, 25315 }, -- Renew
	[17] = { 17, 592, 600, 3747, 6065, 6066, 10898, 10899, 10900, 10901 }, -- Power Word: Shield
	[1022] = { 1022, 5599, 10278 }, -- Blessing of Protection
	[6940] = { 6940, 20729 }, -- Blessing of Sacrifice
};