VUHDO_RANGE_SPELLS_REMAP = {
	["HELPFUL"] = { },
	["HARMFUL"] = { },
};

VUHDO_PET_RANGE_SPELLS = {
	["HUNTER"] = 136,
	["WARLOCK"] = 755,
};

VUHDO_RESURRECTION_RANGE_SPELLS = {
	["DRUID"] = VUHDO_SPELL_ID.REBIRTH,
	["PRIEST"] = VUHDO_SPELL_ID.RESURRECTION,
	["PALADIN"] = VUHDO_SPELL_ID.REDEMPTION,
	["SHAMAN"] = VUHDO_SPELL_ID.ANCESTRAL_SPIRIT,
};
