--
VUHDO_INIT_PURGE_ABILITIES = {
	["WARRIOR"] = { },
	["ROGUE"] = { },
	["HUNTER"] = {
		[VUHDO_DEBUFF_TYPE_ENRAGE] = { 19801 }, -- VUHDO_SPELL_ID.TRANQUILIZING_SHOT
	},
	["MAGE"] = { },
	["DRUID"] = { },
	["PALADIN"] = { },
	["PRIEST"] = {
		[VUHDO_DEBUFF_TYPE_MAGIC] = { 527 }, -- VUHDO_SPELL_ID.DISPEL_MAGIC
	},
	["SHAMAN"] = {
		[VUHDO_DEBUFF_TYPE_MAGIC] = { 370 }, -- VUHDO_SPELL_ID.PURGE
	},
	["WARLOCK"] = {
		[VUHDO_DEBUFF_TYPE_MAGIC] = { "*" }, -- Felhunter: Devour Magic
	},
	["DEATHKNIGHT"] = { },
	["MONK"] = { },
	["DEMONHUNTER"] = { },
	["EVOKER"] = { },
};



--
VUHDO_INIT_DISPEL_ABILITIES = {
	["WARRIOR"] = { },
	["ROGUE"] = { },
	["HUNTER"] = { },
	["MAGE"] = {
		[VUHDO_DEBUFF_TYPE_CURSE] = { 475 }, -- VUHDO_SPELL_ID.REMOVE_LESSER_CURSE
	},
	["DRUID"] = {
		[VUHDO_DEBUFF_TYPE_POISON] = { 2893, 8946 }, -- VUHDO_SPELL_ID.ABOLISH_POISON, VUHDO_SPELL_ID.CURE_POISON_DRUID
		[VUHDO_DEBUFF_TYPE_CURSE] = { 2782 }, -- VUHDO_SPELL_ID.REMOVE_CURSE
	},
	["PALADIN"] = {
		[VUHDO_DEBUFF_TYPE_POISON] = { 4987, 1152 }, -- VUHDO_SPELL_ID.PALA_CLEANSE, VUHDO_SPELL_ID.PURIFY
		[VUHDO_DEBUFF_TYPE_DISEASE] = { 4987, 1152 }, -- VUHDO_SPELL_ID.PALA_CLEANSE, VUHDO_SPELL_ID.PURIFY
		[VUHDO_DEBUFF_TYPE_MAGIC] = { 4987 }, -- VUHDO_SPELL_ID.PALA_CLEANSE
	},
	["PRIEST"] = {
		[VUHDO_DEBUFF_TYPE_DISEASE] = { 552, 528 }, -- VUHDO_SPELL_ID.ABOLISH_DISEASE, VUHDO_SPELL_ID.CURE_DISEASE_PRIEST
		[VUHDO_DEBUFF_TYPE_MAGIC] = { 527 }, -- VUHDO_SPELL_ID.DISPEL_MAGIC
	},
	["SHAMAN"] = {
		[VUHDO_DEBUFF_TYPE_DISEASE] = { 2870 }, -- VUHDO_SPELL_ID.CURE_DISEASE_SHAMAN
		[VUHDO_DEBUFF_TYPE_POISON] = { 526 }, -- VUHDO_SPELL_ID.CURE_POISON_SHAMAN
	},
	["WARLOCK"] = {
		[VUHDO_DEBUFF_TYPE_MAGIC] = { "*" }, -- Felhunter: Devour Magic
	},
	["DEATHKNIGHT"] = { },
	["MONK"] = { },
	["DEMONHUNTER"] = { },
	["EVOKER"] = { },
};



VUHDO_SPEC_TO_DEBUFF_ABIL = { };
